# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: hs2-php-8.1/api
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-www}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${APP_XDEBUG_MODE:-develop,debug}'
            XDEBUG_CONFIG: '${APP_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            LOG_CHANNEL: 'stack'
        env_file:
            - .env
        volumes:
            - '.:/var/www/html'
        networks:
            - app
        depends_on:
            - mysql
            - phpmyadmin
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "${DB_HOST:-%}"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
            # - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
            - './docker/create-app-database.sh:/docker-entrypoint-initdb.d/10-create-app-database.sh'
        networks:
            - app
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - ${FORWARD_PHPMYADMIN_PORT:-8002}:80
        networks:
            - app
        environment:
            - PMA_ARBITRARY=1
networks:
    app:
        driver: bridge
volumes:
    mysql:
        driver: local
